README.md
Update the main readme to:
- reference the android-mk branch
- point to the Android C++ demo
- delete instructions and pre-requisites
=> README: link to android-mk branch

audio-echo/app/src/main/AndroidManifest.xml, audio-echo/app/src/main/res/layout/activity_main.xml, audio-echo/app/src/main/res/values/strings.xml
fix the following lint warnings
```
Security
1	Warning AllowBackup: Missing allowBackup attribute
Internationalization
1	Warning RelativeOverlap: Overlapping items in RelativeLayout
Bi-directional Text
1	Warning RtlHardcoded: Using left/right instead of start/end attributes
```
Related #82
=> audio-echo: fix lint warnings

MoreTeapots/app/build.gradle, Teapot/app/build.gradle, audio-echo/app/build.gradle, bitmap-plasma/app/build.gradle, endless-tunnel/app/build.gradle, gles3jni/app/build-11.gradle, gles3jni/app/build-18.gradle, hello-gl2/app/build.gradle, hello-jni/app/build.gradle, hello-thirdparty/app/build.gradle, native-activity/app/build.gradle, native-audio/app/build.gradle, native-codec/app/build.gradle, native-media/app/build.gradle, native-plasma/app/build.gradle, san-angeles/app/build.gradle, sensor-graph/app/build.gradle
With:
```
for f in */app/build.gradle; do sed -e $'s/^.*android.ndk/\
compileOptions.with {\
sourceCompatibility=JavaVersion.VERSION_1_7\
targetCompatibility=JavaVersion.VERSION_1_7\
}\
\
&/' $f; done
```
Closes #43
=> force JavaVersion.VERSION_1_7 for all samples

MoreTeapots/README.md, Teapot/README.md, audio-echo/README.md, bitmap-plasma/README.md, endless-tunnel/README.md, gles3jni/README.md, hello-gl2/README.md, hello-jni/README.md, hello-thirdparty/README.md, native-activity/README.md, native-audio/README.md, native-codec/README.md, native-media/README.md, native-plasma/README.md, san-angeles/README.md, sensor-graph/README.md
The contributing file is one step higher in the hierarchy
=> README: Fixed wrong markdown links

.travis.yml, appveyor.yml, hello-thirdparty/README.md, hello-thirdparty/app/build.gradle, hello-thirdparty/thirdparty/gpg-sdk/build.gradle
Fixes #89
/cc @claywilkinson @rschiu @gcasey
I'm not very familiar with how to set non-library-dependencies between module tasks, let me know if there is a better way.
=> hello-thirdparty: add manual step to run fetch-gpg-sdk

native-plasma/app/src/main/jni/plasma.c
This ndk example has never worked on my Nexus 7 2013, although it works on my Galaxy S3 for some reason. I finally decided to try and fix it.
If on the Galaxy S3 I increment the time_ms variable to be near the value which the Nexus 7 assigns time_ms, the plasma will not animate. Likewise if on the Nexus 7 I decrement the time_ms variable to be near the value which the Galaxy S3 assigns time_ms, the plasma will animate.
So instead of using just any time spit out by clock_gettime(), I decided to use the time since start of program.
This is my first contribution to any code online ever ;) Hope it helps!
=> Fixed error where the plasma does not animate on some devices.

hello-thirdparty/app/build.gradle, hello-thirdparty/app/src/main/AndroidManifest.xml, hello-thirdparty/build.gradle, hello-thirdparty/gradle/wrapper/gradle-wrapper.properties, hello-thirdparty/thirdparty/gpg-sdk/build.gradle
Hi,
Here is a summary of the changes:
- bumped Google Play Services version to 8.3.0 and Play Games lib version to 2.0
- fixed crash at launch
- bumped gradle version to 2.9
- migrated native dependency declaration to the new gradle system supported in gradle-experimental:0.6.0-alpha2 and cleaned up the app build.gradle accordingly
- added support for all the architectures supported by Google Play Game
Services
Note: To make it work in Android Studio 2.0, I had to deactive Instant Run for the project.
=> port hello-thirdparty to use new 0.6.0 native dependencies system

hello-thirdparty/app/build.gradle, hello-thirdparty/build.gradle
The bug https://code.google.com/p/android/issues/detail?id=196065 has been resolved: the linkage type has to be declared at the dependency level too. I've fixed the code accordingly.
=> fix static linkage declaration in hello-thirdparty

MoreTeapots/app/src/main/jni/ndk_helper/GLContext.cpp, Teapot/app/src/main/jni/ndk_helper/GLContext.cpp, endless-tunnel/app/src/main/jni/native_engine.cpp, hello-thirdparty/app/src/main/jni/main.cpp, native-activity/app/src/main/jni/main.c
- We don't have to call the API unless want to have different buffer size than
the native resolution.
- This was causing broken rendering on some devices.
=> Remove unnecessary ANativeWindow_SetBuffersGeometry() call.

endless-tunnel/app/src/main/jni/util.hpp
the default parameter swapped the order for up/low bound in Random()
by mistake, this fixes it.
=> Fix issues/192

native-media/README.md, native-media/app/src/main/java/com/example/nativemedia/NativeMedia.java
Since M still works for native player, enable it and added a line in README.md to notify android-N issue. tracking with bug https://code.google.com/p/android/issues/detail?id=209410 and internal bug id 28666655
=> re-enable native player for native-media

hello-jni/app/build.gradle
if version is too low (lower than the supporting for 64),
all 64 bit ABI will not build and run anymore.
It is a big problem than just reverting this sample, need find a better way to handle it: one way or the other it has to break someone...
=> Revert platformVersion from Hello-Jni:

README.md, REFERENCE.md
1) updated README.md to include hello-jni codelab which includes debug step inside Android Studio
2) added REFERENCE.md to put down gradle debugging flags
This is to solve https://github.com/googlesamples/android-ndk/issues/20
Plan: from here we add important gradle settings into REFERENCE.md, and hope someday it will be a thorough document. The format of the REFERENCE.md might change as we move along, the content should stay relevant.
Please review and comment whether this strategy could satisfy our needs, thank you very much!
=> adding debug related info

native-activity/app/build.gradle, native-activity/gradle.properties
if we have sourceSets.main.jni.srcDirs = [], then gradle.properties is not needed
=> removing comment about gradle.properties, no code changes

MoreTeapots/app/build.gradle, Teapot/app/build.gradle, choreographer-30fps/app/build.gradle, endless-tunnel/app/build.gradle, gles3jni/app/build-11.gradle, gles3jni/app/build-18.gradle, hello-gl2/app/build.gradle
this is to fix the issue: 
https://github.com/googlesamples/android-ndk/issues/207
there is no such compiling flags anymore in future ndk releases
=> remove hard float compiling flags: compiling flags are gone

.gitignore, audio-echo/app/build.gradle, cmake/README.md, cmake/Teapot/build.gradle, cmake/build.gradle, cmake/endless-tunnel/build.gradle, cmake/hello-jni/build.gradle, cmake/hello-jniCallback/build.gradle, cmake/hello-libs/build.gradle
It is not-backward compatible for cmake project:
with android studio 2.2.0 alpha1 -- alpha4:  use code before this checkin
with android studio 2.2.0 alpha5 and after:     this checkin and after
=> update build to android studio 2.2.0 alpha5.

hello-libs/app/src/main/cpp/hello-libs.cpp
using standard C++ headers, instead of c headers to fix PRIu64 issue
=> fixed issue https://github.com/googlesamples/android-ndk/issues/263:

sensor-graph/accelerometer/src/main/cpp/sensorgraph.cpp
The NDK documentation was not clear, but you are supposed to set the event rate
on an ASensorEventQueue only after enabling its associated sensor. It also needs
to be re-set after re-enabling the sensor. Without it, events arrive at some
"default rate" (quite slowly on some devices).
=> Set event rate after enabling sensor so it takes effect.

README.md
http://tools.android.com/tech-docs/external-c-builds has a redirector gadget. The gadget is broken, but the source has a reference to https://developer.android.com/studio/projects/add-native-code.html, so I guess that's the right place.
=> Fix an outdated link in README.md

audio-echo/app/src/main/cpp/audio_common.h, audio-echo/app/src/main/cpp/audio_player.h, endless-tunnel/app/src/main/cpp/common.hpp, native-activity/app/src/main/cpp/main.cpp, teapots/common/ndk_helper/shader.cpp
1) included OpenSLES.h BEFORE OpenSLES_Android.h
OpenSLES.h inclusion is removed from OpenSLES_Abndroid.h
2) added stdlib.h/cstdlib concerning malloc for sample
endless tunnel
native-activity
teapots derivative samples
Related info: 
https://android.googlesource.com/platform/ndk.git/+/ndk-r14-release/docs/UnifiedHeaders.md
@hak @bbilodeau @qchong @DanAlbert please help take a look, thanks!
=> Fix unified header related issues:

teapots/choreographer-30fps/build.gradle, teapots/more-teapots/build.gradle
removing gcc: it is not supported
@bbilodeau @danalbert, please have review, thank you!
=> Use clang to build teapot samples

hello-cdep/README.md, hello-cdep/app/build.gradle, hello-cdep/app/src/main/cpp/hello-cdep.cpp, hello-cdep/cdep.yml
quick update for hello-CDep for x86 ABIs, and also changes hosting repo to "hello-cdep"
=> Update hello-cdep to include all ABIs

gles3jni/app/src/main/java/com/android/gles3jni/GLES3JNIView.java
This will fix issue #398 
This example is supposed to show how to use GL ES3 rendering.
Yet, it will only request GL ES2 contexts, so never actually creates an ES3 Renderer object.
By selecting the correct GL ES Context, the app will now properly use the ES3 rendering code.
=> Request an ES3 context, not an ES2 context.

teapots/build.gradle
com.android.support:appcompat-v7 is no longer available
on the Android SDK off-line repository, it needs to be
downloaded from the google online repository instead
=> Add google maven repository declaration

teapots/choreographer-30fps/build.gradle, teapots/choreographer-30fps/src/main/cpp/ChoreographerNativeActivity.cpp, teapots/choreographer-30fps/src/main/java/com/sample/choreographer/ChoreographerNativeActivity.java
Timestamp from vblank needs to pass from Java side to JNI on API-16/17/18 to get the correct rendering frames.
@bbilodeau  please take a look, thanks!
=> pass choreopher timestamp from java to jni to get correct 30 fps

camera/basic/src/main/cpp/image_reader.cpp, camera/basic/src/main/cpp/image_reader.h
As this being a very main source for anyone learning to use the Native Camera API calls it would be nice to show more information that if they plan to do real time processing that they should not be using `AImageReader_acquireNextImage` as it will cause huge delay when scaling up resolution of preview. Just adding the extra comment and function can help prevent searching and trying to debug why there is such a random image delay
=> Camera: added GetLatestImage method

camera/basic/src/main/cpp/camera_manager.cpp, camera/texture-view/src/main/cpp/camera_manager.cpp
Looping all entry count is too long and the extracted values might not be expected.
` entry.count` has the total number of entry.
=> camera/**/camera_manager.cpp: iterate entry properly

hello-jniCallback/app/src/main/cpp/hello-jnicallback.c
The ```pthread_attr_t``` struct should be destroyed properly.
=> destroy the thread attributes properly

hello-jni/app/build.gradle, hello-jni/build.gradle, hello-jni/gradle/wrapper/gradle-wrapper.properties
adding '[flavorDimensions](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html?utm_source=android-studio#variant_aware)' for for hello-jni for Android Studio 3.0 requirements. @rschiu, @jomof, @qchong may you kindly take a look?
=> Update build for Android Studio 3.0

hello-libs/README.md
Fix https://github.com/googlesamples/android-ndk/issues/459.  The documentation is wrong actually ( not just "failed to mention..." ). Fixed with PR,  if Studio's cmake port could directly pack it, that would be handy.
@mondaugen  please take a look.
=> Fix wrong doc in hello-libs' README.md

README.md, other-builds/ndkbuild/bitmap-plasma/app/Android.mk, other-builds/ndkbuild/gles3jni/app/Android.mk, other-builds/ndkbuild/hello-gl2/app/Android.mk, other-builds/ndkbuild/hello-jni/app/Android.mk, other-builds/ndkbuild/hello-libs/app/Android.mk, other-builds/ndkbuild/hello-neon/app/Android.mk, other-builds/ndkbuild/native-activity/app/Android.mk, other-builds/ndkbuild/native-audio/app/Android.mk, other-builds/ndkbuild/native-codec/app/Android.mk, other-builds/ndkbuild/native-media/app/Android.mk, other-builds/ndkbuild/native-plasma/app/Android.mk, other-builds/ndkbuild/san-angeles/app/Android.mk, other-builds/ndkbuild/teapots/classic-teapot/Android.mk, other-builds/ndkbuild/teapots/more-teapots/Android.mk
tested: Windows & Mac OS
This is mainly to fix ndk-build under windows. The 240 is magic number for file path, abspath helps. refer to:
http://gnu-make.2324884.n4.nabble.com/using-realpath-abspath-in-3-81-td13798.html
at the bottom of the thread is the workaround, works fine for this case.
=> add abspath workaround for windows ndk-build projects

gles3jni/app/build.gradle, gles3jni/app/src/main/cpp/gles3jni.h
mainly to address issue: https://github.com/googlesamples/android-ndk/issues/350
There is validation usage for various ndk versions, but the sample content no change ( not exploring any of the new functionalities inside gles32)
=> Minor update gles3jni to use version 3.2 headers for API 24+

display-p3/image-view/src/main/cpp/WideColorCtx.cpp
Set color component type to fload for FP16 not 10:10:10:2.
Also set color component type to fixed for all other modes just to
be complete.
=> Set float when requesting FP16 pixel format

san-angeles/app/build.gradle
The ndk-build version of this sample already has this list of ABIs:
include 'armeabi-v7a', 'arm64-v8a', 'x86'
Bug: https://github.com/googlesamples/android-ndk/issues/505
=> Remove mips from san-angeles' ABI list.

endless-tunnel/.google/packaging.yaml, native-activity/.google/packaging.yaml, native-plasma/.google/packaging.yaml, webp/.google/packaging.yaml
=> Removed native-activity & endless-tunnel from Java sample list

webp/view/src/main/cpp/CMakeLists.txt
The master branch fails to build for me atm. In general I think it's a good idea to stick to a specific version, as the master branch might not be stable enough and to make the build reproducible.
=> Clone 1.0.0 branch of libwebp instead of master

hello-libs/gen-libs/src/main/cpp/gmath/src/gmath.h, hello-libs/gen-libs/src/main/cpp/gperf/src/gperf.h
minor change to use
```
extern "C" {
```
block.  Related issue: https://github.com/googlesamples/android-ndk/issues/560
=> Minor update to hello-libs

teapots/choreographer-30fps/src/main/cpp/CMakeLists.txt, teapots/classic-teapot/src/main/cpp/CMakeLists.txt, teapots/more-teapots/src/main/cpp/CMakeLists.txt, teapots/textured-teapot/src/main/cpp/CMakeLists.txt
Among different projects that share on common module ( ndk_helper ), one project's build for ndk_helper actually not usable for other projects' dependency logic decision! In this project, it has 4 sub-project share one ndk_helper, if put it into the common binary into a dir NOT project dependent, every time building apks,  each APK activates one ndk_helper(so it got built 4 times every time ).
With the change, only the first time it will build 4 times, follow-up build will not re-build un-necessary ndk_helper module anymore.
the symptoms is same for desktop CMake projects: this change is necessary.
=> Fix unnecessary re-build for ndk_helper under teapots sample

native-media/app/src/main/cpp/android_fopen.c, native-media/app/src/main/cpp/native-media-jni.c, native-media/app/src/main/java/com/example/nativemedia/NativeMedia.java
This is to fix issue https://github.com/googlesamples/android-ndk/issues/571:
should use application's assetManager, not Activity's assetManager to avoid being garbage collected
=> NativeMedia sample: use application's assetManager

.ci_tools/setup_env.sh
inspired by: https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash
Fact: constraintLayout 1.0.2+ could not be installed by sdkmanager, actually no need to install anymore.
=> CI script update: no need to install with constraintLayout 1.0.2+

hello-oboe/app/src/main/cpp/CMakeLists.txt
fix issue: https://github.com/googlesamples/android-ndk/issues/649
When oboe-stable branch 1.3.0 is released, will change to that one. For now fixing to the latest HASH as of TODAY.
=> hello-oboe: add specific oboe-lib version to use

hello-libs/app/build.gradle, hello-libs/build.gradle, hello-libs/gen-libs/src/main/cpp/CMakeLists.txt, hello-libs/gradle/wrapper/gradle-wrapper.properties
Changes:
1. Bring back strong dependency from "gen-libs" module in "app" module (workaround is not needed anymore)
2. Make it possible to do repeated (incremental) build, when libraries are build as well. It might be not so interesting in the context of this sample project, but it is very helpful in real projects which build native libraries along with Java code, rather than using pre-built lib versions. This is usually the case when such library is only being developed for some particular app.
After updating to new Gradle plugin, the "wrong format" issue is reproducing with 100% probability, that's why I decided to send those patches (which help in my pet project), and that's why I included Gradle plugin update patch in this patch series.
See commit messages for details.
=> Improve libraries build code

teapots/textured-teapot/src/main/assets/Shaders/Cubemap.fsh
Some GPU devices likes ARM Mali midgard would fail
in compiling this shader.
Qualcomm adreno seems free of this problem.
Signed-off-by: Hsia-Jun Li(Randy) <ayaka@soulik.info>
=> teapot: fix missing precision qualifier

other-builds/ndkbuild/bitmap-plasma/app/Android.mk, other-builds/ndkbuild/common.mk, other-builds/ndkbuild/gles3jni/app/Android.mk, other-builds/ndkbuild/hello-gl2/app/Android.mk, other-builds/ndkbuild/hello-jni/app/Android.mk, other-builds/ndkbuild/hello-libs/app/Android.mk, other-builds/ndkbuild/hello-neon/app/Android.mk, other-builds/ndkbuild/native-activity/app/Android.mk, other-builds/ndkbuild/native-audio/app/Android.mk, other-builds/ndkbuild/native-codec/app/Android.mk, other-builds/ndkbuild/native-media/app/Android.mk, other-builds/ndkbuild/native-plasma/app/Android.mk, other-builds/ndkbuild/nn_sample/app/Android.mk, other-builds/ndkbuild/san-angeles/app/Android.mk, other-builds/ndkbuild/teapots/classic-teapot/Android.mk, other-builds/ndkbuild/teapots/more-teapots/Android.mk
This workaround for a bug in abspath used to workaround path length
issues in Windows is not needed in r21+ because the abspath bug was
fixed. Unfortunately the bug being fixed means that the workaround now
introduces a bug when forming the path. Only use the workaround for
pre-r21 NDKs.
Bug: http://b/142666190
=> Drop bug in workaround for r21+.

endless-tunnel/README.md
Encountered some nits in the doc while playing with the sample.
=> Fix file and class names in endless-tunnel readme

prefab/curl-ssl/README.md
Just incorporate https://github.com/android/ndk-samples/issues/740 into [README.md](https://github.com/android/ndk-samples/blob/master/prefab/curl-ssl/README.md)
=> Update prefab sample's README.md to workaround SSL and LLDB conflict

camera/common/utils/camera_utils.cpp, camera/texture-view/src/main/cpp/camera_manager.cpp, camera/texture-view/src/main/cpp/camera_manager.h
Few type mismatch warnings are fixed for project `ndk-samples/camera/texture-view`. 
Unit Test: Compiled it locally and the warnings are gone. 
Note: Camera `exposureTime_` is measured in `ns` and it cannot be negative but the specs consider it to be `signed` it should be `unsigned`. Same is for `sensitivity_` too.
=> Few types mismatch warnings fixed.

camera/build.gradle
Android Studio giving warning about this deprecation:
http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Replaced with mavenCentral().
Tested for both basic and texture-view modules on Pixel3 running Android 11. 
Android Studio version 4.2.1 .
=> removed jcenter() from gradle project file, replaced with mavenCentral() fixes #801

display-p3/image-view/src/main/cpp/ColorSpaceTransform.cpp
Use P3 (D65) XYZ <-> RGB conversion matrix in display-p3 sample instead of the one currently being used, which is for P3 (DCI) XYZ <-> RGB conversion.
BTW, all the matrices in display-p3 sample are updated to high precision floats (rounded to 10 decimal digits).
=> Correct the matrix used in Display P3 XYZ <-> RGB conversion

gles3jni/app/build.gradle, gles3jni/app/src/main/AndroidManifest.xml, other-builds/ndkbuild/gles3jni/app/AndroidManifest.xml, other-builds/ndkbuild/gles3jni/app/build.gradle
=> Fix lint errors for gles3jni.

native-midi/app/build.gradle, native-midi/app/src/main/AndroidManifest.xml
=> Fix lint errors for native-midi.

native-media/app/build.gradle, native-media/app/src/main/AndroidManifest.xml, other-builds/ndkbuild/native-media/app/build.gradle
=> Fix lint errors for native-media.

prefab/curl-ssl/app/build.gradle, prefab/curl-ssl/app/src/main/AndroidManifest.xml
=> Fix lint errors for curl-ssl.

prefab/prefab-publishing/mylibrary/build.gradle
=> Fix lint errors for prefab-publishing.

camera/.google/packaging.yaml, exceptions/.google/packaging.yaml, native-codec/.google/packaging.yaml, native-media/.google/packaging.yaml, unit-test/.google/packaging.yaml
Remove the following from Android Studio, since they use deprecated APIs: audio-echo, native-audio.
Add the following samples to Android Studio: camera, exceptions, native-audio, native-codec, native-media, unit-test.
=> Update samples in Android Studio.

.ci_tools/setup_env.sh, .github/workflows/build.yml
From the action's docs I don't think sdkmanager is actually unavailable, just obnoxious to find (seems the SDK moved that component to `cmdline-tools/$VERSION/bin`, and I've got no idea how to guess the version).
We could make broader use of this by moving the guts of `setup_env.sh` into build.yml, but to do that we'd have to remove the auto-detection of which NDK versions we need (though that's a bug anyway, AGP's supposed to be installing those for us). For now, just unbreak CI and we can deal with that later if it's ever worth doing.
=> Use setup-android to make sdkmanager available.

sanitizers/app/build.gradle
[Why]
Property useLegacyPackaging determin whether to use the legacy convention of compressing all .so files in the APK. If null, .so files will be uncompressed and page-aligned when minSdk >= 23. Otherwise, it failed with "INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2" when minSdk >= 23.
And wrap.sh is only available for API level 27 and above.
[How]
Set useLegacyPackaging to true.
Set compileSdk to 27.
[Reference]
https://developer.android.com/ndk/guides/asan
=> Sanitizer: Set useLegacyPackaging for asan

endless-tunnel/app/src/main/cpp/input_util.cpp
On pixel 7, we get src=0x5002 which means:
touchscreen | stylus | pointer.
=> Fix touch input for Pixel 7

native-activity/app/build.gradle, native-activity/app/src/main/cpp/main.cpp, other-builds/ndkbuild/native-activity/app/build.gradle
The apparent change in `minSdkVersion` here isn't actually changing much. The NDK hasn't supported ICS in a long time, and 21 is the minimum for modern NDKs (though I think this sample is still using an NDK that supports 19, it won't soon). The raise is needed for `android_set_abort_message`.
=> Move sensor handling to a callback.

native-activity/app/src/main/cpp/main.cpp
It looks like whoever wrote this just kept adding draw calls until it worked. For some reason if I removed the call from `APP_CMD_INIT_WINDOW` (which really shouldn't have needed to render), or added an `if (!animating)` early exist to engine_draw_frame, it would prevent the app from *ever* rendering. I never figured out why, but in any case the most important call is the one that was missing: the one in `APP_CMD_GAINED_FOCUS`. That's why the rendering wouldn't start until you tapped the screen. I added that and now all the calls that appear superfluous in fact are.
Depends on https://github.com/android/ndk-samples/pull/1005.
=> Remove odd engine_draw_frame call patterns.

native-activity/app/src/main/cpp/main.cpp
ALooper_pollAll can't be called safely and is being removed from the NDK. Replace with ALooper_pollOnce.
=> Replace ALooper_pollAll with ALooper_pollOnce.

camera/basic/src/main/cpp/android_main.cpp, display-p3/image-view/src/main/cpp/AndroidMain.cpp, endless-tunnel/app/src/main/cpp/native_engine.cpp, hello-vulkan/app/src/main/cpp/vk_main.cpp, native-plasma/app/src/main/cpp/plasma.c, sensor-graph/accelerometer/src/main/cpp/sensorgraph.cpp, teapots/choreographer-30fps/src/main/cpp/ChoreographerNativeActivity.cpp, teapots/classic-teapot/src/main/cpp/TeapotNativeActivity.cpp, teapots/image-decoder/src/main/cpp/TeapotNativeActivity.cpp, teapots/more-teapots/src/main/cpp/MoreTeapotsNativeActivity.cpp, teapots/textured-teapot/src/main/cpp/TeapotNativeActivity.cpp, webp/view/src/main/cpp/webp_view.cpp
There's a fair amount of absurd stuff left around the code I touched. Some samples have a lot of code dedicated to managing sensors that then do nothing with the sensors, some display a static image but have a render "loop", all of these have a nearly identical main loop but don't share any code, etc. I'll be back.
=> Migrate samples off ALooper_pollAll.

camera/basic/src/main/cpp/image_reader.cpp
The U and V planes are swapped [here](https://github.com/android/ndk-samples/blob/main/camera/basic/src/main/cpp/image_reader.cpp#L257):
AImage_getPlaneData(image, 0, &yPixel, &yLen);
AImage_getPlaneData(image, 1, &vPixel, &vLen);
AImage_getPlaneData(image, 2, &uPixel, &uLen);
According to [the docs](https://developer.android.com/ndk/reference/group/media#group___media_1gga9c3dace30485a0f28163a882a5d65a19aea9797f9b5db5d26a2055a43d8491890):
> The order of planes is guaranteed such that plane #0 is always Y, plane #1 is always U (Cb), and plane #2 is always V (Cr).
This works out because [the function YUV2RGB](https://github.com/android/ndk-samples/blob/main/camera/basic/src/main/cpp/image_reader.cpp#L193) actually encodes BGRA, not RGBA:
return 0xff000000 | (nR << 16) | (nG << 8) | nB; …
=> Get U/V planes instead of V/U, and encode RGBA instead of BGRA.

orderfile/app/build.gradle
Fixes the lint task that's complaining that this app wouldn't be allowed in Play.
=> Update orderfile sample to targetSdk 34.

sanitizers/app/.gitignore, sanitizers/app/src/asan/jniLibs/.gitignore
This was previously only scoped to ASan. Move it up to the module directory so it covers all variants.
=> Cover ubsan libraries with gitignore.

exceptions/build.gradle
Not actually a proper upgrade, but the other samples that use Kotlin are all on 1.7.21.
=> Update Kotlin to match the rest of the samples.

native-audio/app/build.gradle, native-audio/gradle.properties
gradle.properties, afaict, can't be applied per module. Once these are all in one giant project we want to apply this property at a finer scope than globally, so move it to buildFeatures, which are preferred anyway.
=> Switch to buildFeatures for BuildConfig flag.

hello-vulkan/app/build.gradle, hello-vulkan/build.gradle, hello-vulkan/settings.gradle
Combining all the samples into one project means they have to all use the same Kotlin plugin version, which is 1.7.21 for all the others.
=> Downgrade hello-vulkan's kotlin to match the other samples.

build-logic/build.gradle.kts, build-logic/src/main/java/com/android/ndk/samples/buildlogic/AndroidApplicationConventionPlugin.kt, build-logic/src/main/java/com/android/ndk/samples/buildlogic/KotlinConventionPlugin.kt, build-logic/src/main/java/com/android/ndk/samples/buildlogic/Versions.kt, exceptions/app/build.gradle, gradle/libs.versions.toml
Needs another convention for Kotlin stuff to keep the Java/Kotlin versions in sync.
Depends on https://github.com/android/ndk-samples/pull/1030.
=> Migrate a kotlin sample to the convention plugin.

.github/workflows/build.yml
I'm tired of waiting for the build to finish only to learn that my markdown isn't markdowny enough.
=> Move the fast part of the "build" sooner.

orderfile/app/build.gradle
AGP uses the latest available by default, which is what we want.
=> Remove no-op build option.

.pre-commit-config.yaml
mdformat is a jerk and wants to change the case of links. I'll be back to re-apply prettier if we think we need it.
=> Disable mdformat check.

README.md
Some of this is quite old. Links to YouTube videos from 2015 and websites that don't exist any more aren't so useful. Update and rearrange.
Still lacking is an ARCHITECTURE.md that explains the repo layout. I'll do that next.
=> Improve the README.

README.md
We should fix this, but for now let's be honest.
Depends on https://github.com/android/ndk-samples/pull/1043
=> Warn about production quality in the readme.

.github/workflows/build.yml
`[ main develop ]` is not a list of "main" and "develop", it's a list of "main develop". There is no branch named "main develop". This has been wrong since it was originally checked in a few years ago, so checks just have not been running on push.
The branch filtering is totally unnecessary. Just remove it.
This, it turns out, is the real reason that the badge shows "no status". It's right. This build has never run, so there is no status yet.
=> Fix the build workflow to actually run on push.

camera/basic/src/main/cpp/camera_ui.cpp, camera/basic/src/main/java/com/sample/camera/basic/CameraActivity.java
Pre-work for https://github.com/android/ndk-samples/issues/1031. For some reason the UI for the storage permission isn't shown whenever targetSdkVersion is 33+, and it's just returning a denial. This sample is badly structured such that if either permission isn't granted, the UI init will never run. The two permissions requests really ought to be decoupled (the viewfinder should still work even if I never try to save a photo), and the UI should tell the user why it failed. For now I'm just making it fail more violently, because the lack of any error or logging is what made this a multi-hour debugging experience instead of the now obvious problem.
=> camera:basic: fail if permissions are not granted

teapots/textured-teapot/src/main/cpp/TeapotRenderer.cpp, teapots/textured-teapot/src/main/cpp/TeapotRenderer.h, teapots/textured-teapot/src/main/cpp/Texture.cpp, teapots/textured-teapot/src/main/cpp/Texture.h, teapots/textured-teapot/src/main/cpp/TexturedTeapotRender.cpp, teapots/textured-teapot/src/main/cpp/TexturedTeapotRender.h
Whoever wrote this wrote some general purpose texture and renderer classes... which they then copy pasted into each sample. This sample only ever uses a cubemap texture, so delete the other paths and remove the error handling code for a thing that will never happen.
The original intent was good, but it's pointless when the three teapots samples (classic, textured, and image-decoder) are three samples that don't share this "common" code. I suspect I'll merge the three at some point, but I don't really like how this particular interface was shaped anyway, so I'll probably rewrite that when I do.
=> textured-teapot: remove dead code

camera/texture-view/src/main/AndroidManifest.xml
This was probably copied from the other camera sample that supports saving images. This one does not, and even if it did, that permission hasn't been needed since KitKat anyway.
=> camera:texture-view: remove unused permission

camera/basic/src/main/AndroidManifest.xml, camera/basic/src/main/java/com/sample/camera/basic/CameraActivity.java
Not needed for writing to the SD card since KitKat, and the permission is auto-denied for targetSdkVersion 33+:
https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE
This isn't really the right way to do this though. We're supposed to do https://developer.android.com/training/data-storage/use-cases?utm_source=lint&utm_medium=lint&utm_campaign=lint#capture-image-media
Fixes https://github.com/android/ndk-samples/issues/1031
=> camera:basic: don't request WRITE_EXTERNAL_STORAGE

build-logic/src/main/java/com/android/ndk/samples/buildlogic/Versions.kt
I didn't want to do this with a beta, but I think it's reasonable for us to adopt the release candidates.
=> Upgrade to NDK r27 RC 1.

.clang-format
Deriving pointer alignment essentially makes this do nothing, since for whatever reason (fighting with Studio maybe?), for new files it's deriving the wrong style.
=> Fix .clang-format to not preserve bad format.

README.md
Move build status badge down into the "Build and Run" section to avoid it being pulled in as part of the repository description by automation.
Bug: 350055171
=> Move build status badge in README

unit-test/app/build.gradle
Fixes https://github.com/android/ndk-samples/issues/1083.
=> Use testOnly in unit-test sample.

.github/workflows/build.yml
This PR standardizes GitHub Actions triggers in workflow files within `.github/workflows/`.
The goal is to ensure workflows run consistently on `push`, `pull_request`, and `workflow_dispatch` events where appropriate.
This is part of a batch of pull requests across repositories owned by the `android` organization on GitHub.
**Project Owner:** Please review the changes carefully to ensure they are correct and appropriate for this project before approving and merging.
* If you do not think this change is appropriate (e.g., a workflow should NOT run on one of these triggers), please leave a comment explaining why.
* If you think the goal is appropriate but notice a mistake in the implementation, please leave a comment detailing the mistake.
=> Add triggers to .github/workflows/

hello-jni/README.md
current description could be interpreted as "open hello-jni" directory instead of its parent dir
=> clarify hello-jni/README.md

bitmap-plasma/app/src/main/cpp/CMakeLists.txt, camera/basic/src/main/cpp/CMakeLists.txt, camera/texture-view/src/main/cpp/CMakeLists.txt, endless-tunnel/app/src/main/cpp/CMakeLists.txt, gles3jni/app/src/main/cpp/CMakeLists.txt, hello-gl2/app/src/main/cpp/CMakeLists.txt, hello-jniCallback/app/src/main/cpp/CMakeLists.txt, hello-libs/app/src/main/cpp/CMakeLists.txt, hello-neon/app/src/main/cpp/CMakeLists.txt, native-activity/app/src/main/cpp/CMakeLists.txt, native-audio/app/src/main/cpp/CMakeLists.txt, native-media/app/src/main/cpp/CMakeLists.txt, native-plasma/app/src/main/cpp/CMakeLists.txt, nn-samples/basic/src/main/cpp/CMakeLists.txt, nn-samples/sequence/src/main/cpp/CMakeLists.txt, san-angeles/app/src/main/cpp/CMakeLists.txt, sensor-graph/accelerometer/src/main/cpp/CMakeLists.txt
CMake really wants us to include this for some reason. I'm not sure why, but it's easy enough to shut up.
Some reformatting included because I can't be bothered to turn off the IDE's auto-formatter depending on whether I'm in a sample that's already been cleaned up or not.
=> Fix all missing project warnings.

audio-echo/app/src/main/cpp/CMakeLists.txt, audio-echo/app/src/main/cpp/audio_effect.cpp, audio-echo/app/src/main/cpp/audio_effect.h, audio-echo/app/src/main/cpp/audio_main.cpp, audio-echo/app/src/main/cpp/buf_manager.h
Add -Wextra, use add_compile_options instead of target_compile_options so it affects the whole file (there's only one target here so it makes no difference, but it's safer for copying), and fix the issues:
1. A function that took an int32_t for comparison with other unsigned types, despite the only caller passing a uint32_t that was being narrowed anyway.
2. A bunch of unused arguments.
3. Removed some unused code that had warnings rather than fixing it.
=> Increase warning level for audio-echo.

build-logic/src/main/java/com/android/ndk/samples/buildlogic/Versions.kt, vectorization/src/main/cpp/benchmark.cpp, vectorization/src/main/cpp/matrix.h
I was planning to leave this on the LTS, but
https://github.com/android/ndk/issues/2100 is really annoying now that I've updated CMake.
=> Update NDK to r28c.

native-audio/app/src/main/cpp/CMakeLists.txt, native-audio/app/src/main/cpp/native-audio-jni.cpp
I'd originally thought I'd just end up deleting this sample since it uses the deprecated OpenSLES, but this sample has more features than hello-oboe does so I'll probably migrate it to Oboe later and delete hello-oboe instead.
For now, I've made the following cleanups:
1. Migrate to C++
2. Migrate to `add_app_library()` to increase the warning level
=> Cleanups in native-audio.

native-codec/app/src/main/cpp/CMakeLists.txt
I'd missed this one somehow when I fixed all the others. Add it to shut up the warning.
=> Add missing project to native-codec.

camera/basic/src/main/cpp/CMakeLists.txt, endless-tunnel/app/src/main/cpp/CMakeLists.txt, native-activity/app/src/main/cpp/CMakeLists.txt
These should all just move to GameActivity, but that's a slightly more
involved migration. This is an easy first step to clean up the existing
callers.
=> Simplify native_app_glue uses.
