hello-jni/.google/packaging.yaml
=> hello-jni/packaging: switch to draft

.travis.yml, README.md
=> travis: enable for all gradle project

MoreTeapots/gradle/wrapper/gradle-wrapper.properties, Teapot/gradle/wrapper/gradle-wrapper.properties, bitmap-plasma/gradle/wrapper/gradle-wrapper.properties, endless-tunnel/gradle/wrapper/gradle-wrapper.properties, gles3jni/gradle/wrapper/gradle-wrapper.properties, hello-gl2/gradle/wrapper/gradle-wrapper.properties, hello-jni/gradle/wrapper/gradle-wrapper.properties, native-activity/gradle/wrapper/gradle-wrapper.properties, native-audio/gradle/wrapper/gradle-wrapper.properties, native-codec/gradle/wrapper/gradle-wrapper.properties, native-media/gradle/wrapper/gradle-wrapper.properties, native-plasma/gradle/wrapper/gradle-wrapper.properties, san-angeles/gradle/wrapper/gradle-wrapper.properties
=> update gradle wrapper

MoreTeapots/gradle/wrapper/gradle-wrapper.properties, Teapot/gradle/wrapper/gradle-wrapper.properties, bitmap-plasma/gradle/wrapper/gradle-wrapper.properties, endless-tunnel/gradle/wrapper/gradle-wrapper.properties, gles3jni/gradle/wrapper/gradle-wrapper.properties, hello-gl2/gradle/wrapper/gradle-wrapper.properties, hello-jni/gradle/wrapper/gradle-wrapper.properties, native-activity/gradle/wrapper/gradle-wrapper.properties, native-audio/gradle/wrapper/gradle-wrapper.properties, native-codec/gradle/wrapper/gradle-wrapper.properties, native-media/gradle/wrapper/gradle-wrapper.properties, native-plasma/gradle/wrapper/gradle-wrapper.properties, san-angeles/gradle/wrapper/gradle-wrapper.properties
=> gradle-wrapper: switch to -bin

builder/build.gradle, builder/src/test/java/GradleBuildTest.java
- launch `clean` and `lint` first
- build modified projects first
=> builder: proritize dirty projects

MoreTeapots/build.gradle, Teapot/build.gradle, bitmap-plasma/build.gradle, endless-tunnel/build.gradle, gles3jni/build.gradle, hello-gl2/build.gradle, hello-jni/build.gradle, native-activity/build.gradle, native-audio/build.gradle, native-codec/build.gradle, native-media/build.gradle, native-plasma/build.gradle, san-angeles/build.gradle
=> add jcenter to the default repositories

.travis.yml
=> travis: remove custom gradle repo

.travis.yml, builder/build.gradle, builder/src/test/java/GradleBuildTest.java
=> travis: add console test report

MoreTeapots/build.gradle, Teapot/build.gradle, bitmap-plasma/build.gradle, endless-tunnel/build.gradle, gles3jni/build.gradle, hello-gl2/build.gradle, hello-jni/build.gradle, native-activity/build.gradle, native-audio/build.gradle, native-codec/build.gradle, native-media/build.gradle, native-plasma/build.gradle, san-angeles/build.gradle
=> remove bintray from repo list

builder/build.gradle, builder/src/test/java/GradleBuildTest.java
=> builder: add lint output

.travis.yml, bitmap-plasma/app/build.gradle, hello-gl2/app/build.gradle, hello-jni/app/build.gradle, native-activity/app/build.gradle, native-audio/app/build.gradle, native-codec/app/build.gradle, native-media/app/build.gradle, native-plasma/app/build.gradle, san-angeles/app/build.gradle
targetSdkVersion should be 22.
=> targetSdkVersion should be 22

native-audio/app/build.gradle, native-audio/app/src/main/java/com/example/nativeaudio/NativeAudio.java, native-audio/app/src/main/jni/native-audio-jni.c
please review the fast audio path for buffered queue player creation
=> adding fast audio path when creating buffered queue audio player

MoreTeapots/README.md, Teapot/README.md, audio-echo/README.md, bitmap-plasma/README.md, endless-tunnel/README.md, gles3jni/README.md, hello-gl2/README.md, hello-jni/README.md, native-activity/README.md, native-audio/README.md, native-codec/README.md, native-media/README.md, native-plasma/README.md, san-angeles/README.md
The indent of the outline was wrong.
=> README: fix getting started section

.travis.yml, audio-echo/app/build.gradle, audio-echo/build.gradle
@ggfan this should improve the test output.
@yaraki can you review, since it modify the change you did in #56
=> travis: always display test summary

hello-thirdparty/README.md
s/native-playgameservices/hello-thirdparty/
=> hello-thirdparty: fix typo in README

.travis.yml, builder/src/test/java/GradleBuildTest.java
So that it's easier to add windows build (#80).
=> builder: remove pandoc deps

appveyor.yml, builder/build.gradle, builder/src/test/java/GradleBuildTest.java, gles3jni/README.md, gles3jni/app/build.gradle, gles3jni/app/src/main/AndroidManifest.xml
=> add appveyor configuration

native-audio/app/src/main/java/com/example/nativeaudio/NativeAudio.java, native-audio/app/src/main/res/layout/main.xml, native-audio/app/src/main/res/values/strings.xml
Fix the following lint warning
```
Correctness
2	Warning Assert: Assertions
2	Warning InlinedApi: Using inlined constants on older versions
Internationalization
21	Warning HardcodedText: Hardcoded text
```
=> lint native audio

.travis.yml, MoreTeapots/app/build.gradle, Teapot/app/build.gradle, audio-echo/app/build.gradle, native-audio/app/build.gradle, native-codec/app/build.gradle, native-media/app/build.gradle
```
android-ndk 🍊  grep -l uses-permission */app/src/main/AndroidManifest.xml
MoreTeapots/app/src/main/AndroidManifest.xml
Teapot/app/src/main/AndroidManifest.xml
audio-echo/app/src/main/AndroidManifest.xml
native-audio/app/src/main/AndroidManifest.xml
native-codec/app/src/main/AndroidManifest.xml
native-media/app/src/main/AndroidManifest.xml
```
=> downgrade sample with permissions to 22

CONTRIBUTING.md
=> CONTRIBUTING: remove new sample section

.travis.yml
=> add artifacts

.travis.yml, MoreTeapots/app/build.gradle, Teapot/app/build.gradle, appveyor.yml, audio-echo/app/build.gradle, bitmap-plasma/app/build.gradle, endless-tunnel/app/build.gradle, gles3jni/app/build.gradle, hello-gl2/app/build.gradle, hello-jni/app/build.gradle, hello-thirdparty/app/build.gradle, native-activity/app/build.gradle, native-audio/app/build.gradle, native-codec/app/build.gradle, native-media/app/build.gradle, native-plasma/app/build.gradle, san-angeles/app/build.gradle, sensor-graph/app/build.gradle
=> bump build-tools

MoreTeapots/README.md, README.md, Teapot/README.md, audio-echo/README.md, bitmap-plasma/README.md, endless-tunnel/README.md, gles3jni/README.md, hello-gl2/README.md, hello-jni/README.md, hello-thirdparty/README.md, native-activity/README.md, native-audio/README.md, native-codec/README.md, native-media/README.md, native-plasma/README.md, san-angeles/README.md, sensor-graph/README.md
=> README: add link to gradle experimental docs

README.md
Add links to other android studio samples on github:
google play games, vulkan samples and tutorials
=> main page README.md update

endless-tunnel/app/src/main/jni/data/blurb.inl
No functional change, just wording in the about box.
=> remove gpg reference since there is gpg in this game

native-plasma/app/src/main/jni/plasma.c
this is to fix problem in: 
https://github.com/googlesamples/android-ndk/issues/134
=> Requesting 565 window format in native-plasma to make it work

README.md
this is to address: 
https://github.com/googlesamples/android-ndk/issues/61
=> Update master README.md file for known issues

audio-echo/app/build.gradle, audio-echo/app/src/main/AndroidManifest.xml, audio-echo/app/src/main/java/com/google/sample/echo/MainActivity.java, audio-echo/app/src/main/res/values/strings.xml, native-audio/app/build.gradle, native-audio/app/src/main/java/com/example/nativeaudio/NativeAudio.java, native-audio/app/src/main/res/values/strings.xml
affected audio-echo and native-audio samples
=> light-weighted implementation for run-time permission request

MoreTeapots/app/src/main/AndroidManifest.xml, Teapot/app/src/main/AndroidManifest.xml, native-media/app/src/main/AndroidManifest.xml
Moreteapot
teapot
native-media
=> Remove unnecessary storage access from 3 samples:

bitmap-plasma/app/src/main/jni/plasma.c, native-plasma/app/src/main/jni/plasma.c
it does make it more greenish, I think we should fix it to be real 565 format
=> Fix issue https://github.com/googlesamples/android-ndk/issues/204

hello-jniCallback/app/src/main/cpp/hello-jnicallback.c
also moved mutex manipulation with start/stop tick scope
=> remove JNI_OnUnload(): it never get called

.gitignore, MoreTeapots/build.gradle, Teapot/build.gradle, bitmap-plasma/build.gradle, gles3jni/build.gradle, hello-gl2/build.gradle, hello-jni/build.gradle, hello-neon/build.gradle, native-activity/build.gradle, native-audio/build.gradle, native-codec/build.gradle, native-media/build.gradle, native-plasma/build.gradle, san-angeles/build.gradle, two-libs/build.gradle
simply bump up the plugin version with today's new release. no other changes
Build on Mac fine
=> update to android plugin 2.2.0-alpha4 ( preview 4 )

hello-libs/app/build.gradle, hello-libs/build.gradle, hello-libs/gmath/build.gradle, hello-libs/gperf/build.gradle, hello-libs/gradle.properties, hello-libs/gradle/wrapper/gradle-wrapper.properties
Update to latest gradle tools versions.
Enable daemon gradle setting.
Update SDK version.
=> Update to latest gradle tools versions. Enable daemon gradle setting. Update SDK version.

MoreTeapots/build.gradle, Teapot/build.gradle, bitmap-plasma/build.gradle, gles3jni/build.gradle, hello-gl2/build.gradle, hello-jni/build.gradle, hello-neon/build.gradle, native-activity/build.gradle, native-audio/build.gradle, native-codec/build.gradle, native-media/build.gradle, native-plasma/build.gradle, san-angeles/build.gradle, two-libs/build.gradle
It is not-backward compatible for cmake project:
with android studio 2.2.0 alpha1 -- alpha4:  use code before this checkin
with android studio 2.2.0 alpha5 and after:     this checkin and after
=> update to android studio 2.2.0 alpha5

.gitignore, san-angeles/app/build.gradle, san-angeles/app/src/main/AndroidManifest.xml, san-angeles/build.gradle, san-angeles/gradle/wrapper/gradle-wrapper.properties
=> Fix to san-angeles for master-ndkbuild branch:

.gitignore, san-angeles/README.md, san-angeles/app/build.gradle, san-angeles/app/src/main/AndroidManifest.xml, san-angeles/build.gradle, san-angeles/gradle/wrapper/gradle-wrapper.properties
external build 'path' should be file
add apk split feature
Branch:
master-cmake
Tested:
Mac X build, nexus 6 & emulator for target
=> Fix sample san-angeles for:

.gitignore, cmake/build.gradle, cmake/gen-libs/build.gradle, cmake/gradle/wrapper/gradle-wrapper.properties
Also fix gen-libs for static lib build
=> Update cmake samples to RC2 gradle plugin version

gles3jni/app/build.gradle, gles3jni/app/src/main/cpp/CMakeLists.txt
This PR fixes http://b.android.com/223432
=> Fix the build of the gles3jni sample

gles3jni/app/src/main/cpp/RendererES2.cpp, gles3jni/app/src/main/cpp/RendererES3.cpp
@hak, @courtney-lunarg  Please Take A Look ( PLAT ), thanks
=> Port Courtney's fix of vertex attribute  for gles3init

native-audio/app/src/main/java/com/example/nativeaudio/NativeAudio.java
https://github.com/googlesamples/android-ndk/issues/229
@hak PLAT, thanks
=> Disable uriPlayer from UI to workaround bug:

native-codec/app/src/main/java/com/example/nativecodec/MyGLSurfaceView.java
Related Issue#
https://github.com/googlesamples/android-ndk/issues/324
@ketanm, @bbilodeau, @hak PLAT, thanks
=> Fixing typo in native-codec java source

hello-libs/README.md
=> Fix Android Studio hello-libs import description panel

Teapot/app/src/main/cpp/Android.mk, Teapot/app/src/main/cpp/ndk_helper/Android.mk, Teapot/app/src/main/cpp/ndk_helper/CMakeLists.txt, Teapot/app/src/main/cpp/ndk_helper/GLContext.cpp, Teapot/app/src/main/cpp/ndk_helper/GLContext.h, Teapot/app/src/main/cpp/ndk_helper/JNIHelper.cpp, Teapot/app/src/main/cpp/ndk_helper/JNIHelper.h, Teapot/app/src/main/cpp/ndk_helper/NDKHelper.h, Teapot/app/src/main/cpp/ndk_helper/gestureDetector.cpp, Teapot/app/src/main/cpp/ndk_helper/gestureDetector.h, Teapot/app/src/main/cpp/ndk_helper/gl3stub.c, Teapot/app/src/main/cpp/ndk_helper/gl3stub.h, Teapot/app/src/main/cpp/ndk_helper/interpolator.cpp, Teapot/app/src/main/cpp/ndk_helper/interpolator.h, Teapot/app/src/main/cpp/ndk_helper/perfMonitor.cpp, Teapot/app/src/main/cpp/ndk_helper/perfMonitor.h, Teapot/app/src/main/cpp/ndk_helper/shader.cpp, Teapot/app/src/main/cpp/ndk_helper/shader.h, Teapot/app/src/main/cpp/ndk_helper/tapCamera.cpp, Teapot/app/src/main/cpp/ndk_helper/tapCamera.h, Teapot/app/src/main/cpp/ndk_helper/vecmath.cpp, Teapot/app/src/main/cpp/ndk_helper/vecmath.h
to avoid the bug in InitEGLSurface() to fix bug https://code.google.com/p/android/issues/detail?id=228354
=> Use local copy of ndk_helper instead of NDK's copy

native-media/app/build.gradle, other-builds/experimental/native-media/app/build.gradle, other-builds/ndkbuild/native-media/app/build.gradle
github issue: https://github.com/googlesamples/android-ndk/issues/333
tested: Mac X build + Nexus 6 target
@hak @bbilodeau may you take a look at it, thanks
=> Fix java player problem in native-media sample

MoreTeapots/build.gradle, MoreTeapots/gradle/wrapper/gradle-wrapper.properties, Teapot/build.gradle, Teapot/gradle/wrapper/gradle-wrapper.properties, bitmap-plasma/build.gradle, bitmap-plasma/gradle/wrapper/gradle-wrapper.properties, gles3jni/build.gradle, gles3jni/gradle/wrapper/gradle-wrapper.properties, hello-gl2/build.gradle, hello-gl2/gradle/wrapper/gradle-wrapper.properties, hello-jni/build.gradle, hello-jni/gradle/wrapper/gradle-wrapper.properties, hello-neon/build.gradle, hello-neon/gradle/wrapper/gradle-wrapper.properties, native-activity/build.gradle, native-activity/gradle/wrapper/gradle-wrapper.properties, native-audio/build.gradle, native-audio/gradle/wrapper/gradle-wrapper.properties, native-codec/build.gradle, native-codec/gradle/wrapper/gradle-wrapper.properties, native-media/build.gradle, native-media/gradle/wrapper/gradle-wrapper.properties, native-plasma/build.gradle, native-plasma/gradle/wrapper/gradle-wrapper.properties, two-libs/build.gradle, two-libs/gradle/wrapper/gradle-wrapper.properties
test a couple samples on Android-22 platform, works fine. Built on Mac
@hak PTAL, thank you
=> update to Android Studio 2.2.3

hello-jni/app/build.gradle, hello-jni/app/src/main/java/com/example/hellojni/HelloJni.java, hello-jni/app/src/main/res/layout/activity_hello_jni.xml
@bbilodeau @hak @RogerHardiman, Please Take A Look?  thanks
=> fix issue https://github.com/googlesamples/android-ndk/issues/336

teapots/common/ndk_helper/GLContext.cpp, teapots/common/ndk_helper/JNIHelper.cpp, teapots/common/ndk_helper/JNIHelper.h, teapots/common/ndk_helper/NDKHelper.h, teapots/common/ndk_helper/gestureDetector.cpp, teapots/common/ndk_helper/gestureDetector.h, teapots/common/ndk_helper/gl3stub.c, teapots/common/ndk_helper/gl3stub.cpp, teapots/common/ndk_helper/gl3stub.h, teapots/common/ndk_helper/perfMonitor.cpp, teapots/common/ndk_helper/sensorManager.cpp, teapots/common/ndk_helper/sensorManager.h, teapots/common/ndk_helper/shader.cpp, teapots/common/ndk_helper/tapCamera.cpp, teapots/common/ndk_helper/vecmath.cpp
just ran clang-format -i -style=google for teapot/common/ndk_helper/ for all sources there.  This would pave the way for converging with NDK's copy
=> Update source style in teapot/ndk_helper/ directory, no functional change

gles3jni/app/build.gradle, gles3jni/app/src/main/cpp/CMakeLists.txt
@qchong Please take a look, thanks
=> fix OpenGL2 min android version

teapots/common/ndk_helper/CMakeLists.txt, teapots/common/ndk_helper/tapCamera.cpp, teapots/common/ndk_helper/vecmath.h
Compiler is tighting supportability for earlier versions
to comply with standard
=> Update Teapot sample to use C++11's std::isnan()

san-angeles/app/build.gradle
This has been deprecated for over a year.
=> Stop hard coding GCC.

webp/view/CMakeLists.txt, webp/view/build.gradle, webp/view/src/main/cpp/webp_decode.cpp, webp/view/src/main/cpp/webp_view.cpp
@bbilodeau @danalbert, please take a look at it, thank you so much!
=> fix bug in webp sample for releasing memory and function return type

webp/view/CMakeLists.txt, webp/view/build.gradle
@bbilodeau @jomof @tjohns may you kindly look at it?  thank you
=> Update webp to clone libwebp repo as native code dependency

endless-tunnel/app/build.gradle
fix https://github.com/googlesamples/android-ndk/issues/379.  need to look at others in another time for similar things ( mostly NativeActivity derived samples )
=> fixing github issue #379

teapots/choreographer-30fps/src/main/assets/Shaders/ShaderPlain.fsh, teapots/classic-teapot/src/main/assets/Shaders/ShaderPlain.fsh, teapots/more-teapots/src/main/assets/Shaders/ShaderPlain.fsh, teapots/more-teapots/src/main/assets/Shaders/ShaderPlainES3.fsh, teapots/more-teapots/src/main/assets/Shaders/VS_ShaderPlain.vsh
@hak @bbilodeau please take a look, thx
=> Fixing mis-matching precision for vMaterialSpecular in shaders

native-activity/app/src/main/cpp/CMakeLists.txt, native-activity/app/src/main/cpp/main.cpp, sensor-graph/accelerometer/src/main/cpp/CMakeLists.txt, sensor-graph/accelerometer/src/main/cpp/sensorgraph.cpp, teapots/classic-teapot/src/main/cpp/TeapotNativeActivity.cpp, teapots/common/ndk_helper/sensorManager.cpp, teapots/common/ndk_helper/sensorManager.h, teapots/more-teapots/src/main/cpp/MoreTeapotsNativeActivity.cpp
details are in https://issuetracker.google.com/issues/37324654
@bbilodeau @qchong @DanAlbert PTAL,  thanks
=> workaround ASensorManager_getInstance() deprecation issue in NDK-r15

teapots/choreographer-30fps/src/main/cpp/ChoreographerNativeActivity.cpp
@bbilodeau @hak @qchong PTAL, thx
=> update choreographer-30fps to render according to time-stamp

teapots/common/ndk_helper/JNIHelper.cpp
handles the case when getExternalFilesDir() returns NULL case in JNIHelper this avoid the hang when running on android-17
somehow NativeActivity::getExternalFilesDir() returns back NULL on Android-18/17 on Nexus.  When it happens, the downstream code will have null pointer access violation.
The change just to skip null pointer access cases
@hak @bbilodeau PTAL, thanks
=> JNIHelper update

teapots/choreographer-30fps/src/main/cpp/ChoreographerNativeActivity.cpp
to address code-review
@bbilodeau PTAL, thx
=> teapot project, chorographer-30fps: update comment

audio-echo/app/build.gradle, audio-echo/app/src/main/cpp/audio_main.cpp, audio-echo/app/src/main/cpp/audio_player.cpp, audio-echo/app/src/main/cpp/audio_player.h, audio-echo/app/src/main/cpp/audio_recorder.cpp, audio-echo/app/src/main/java/com/google/sample/echo/MainActivity.java, native-audio/app/src/main/cpp/native-audio-jni.c
This fixes audio-echo issue reported from https://github.com/googlesamples/android-ndk/issues/367.
@dturner , @bbilodeau, PTAL
=> fixing issue in audio-echo

MoreTeapots/app/build.gradle, MoreTeapots/app/src/main/cpp/Application.mk, Teapot/app/build.gradle, Teapot/app/src/main/cpp/Application.mk, san-angeles/app/build.gradle
to make it buildable for NDK-r15 for Teapot and San-Angeles
=> Bump up Android level to 14 in application.mk

hello-jni/app/build.gradle, hello-neon/app/src/main/cpp/CMakeLists.txt, hello-neon/app/src/main/cpp/NEON_2_SSE.h, hello-neon/app/src/main/cpp/helloneon-intrinsics.c
@qchong @bbilodeau PTAL, thanks
=> Hello neon update

hello-jni/app/build.gradle
Info:
https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html?utm_source=android-studio#variant_aware
=> Android Studio 3.0.0 dimension update

bitmap-plasma/app/build.gradle
change android.mk to Android.mk ( case sensitive issue )
=> Sample in branch master-ndkbuild, bitmap-plasma/app/build.gradle

camera/README.md, camera/basic/src/main/cpp/camera_engine.cpp, camera/basic/src/main/cpp/camera_engine.h, camera/basic/src/main/cpp/camera_manager.h, camera/basic/src/main/cpp/camera_ui.cpp, camera/basic/src/main/cpp/image_reader.cpp, camera/basic/src/main/cpp/image_reader.h, camera/basic/src/main/java/com/sample/camera/basic/CameraActivity.java, camera/basic/src/main/res/layout/widgets.xml, camera/texture-view/src/main/cpp/android_main.cpp
https://github.com/googlesamples/android-ndk/issues/425
=> fix github issue 425

native-media/app/src/main/cpp/native-media-jni.c
To fix lockup reported in issue: https://github.com/googlesamples/android-ndk/issues/392
@bbilodeau @qchong PTAL
=> native-media: fix issue 392

camera/basic/src/main/cpp/image_reader.cpp, camera/basic/src/main/cpp/image_reader.h
Moved all ints to int32_t to be type safe and removed assert checking from each seperate present image degree switch function
=> refactored ImageReader::PresentImages

README.md, hello-jni/README.md, hello-libs/settings.gradle
minor changes in readme files:
1) update the codelab to cmake's version
2) integrate code change https://github.com/googlesamples/android-ndk/pull/325 from @isakh ( it has been outstanding there for a long while )
=> Integrate changes from PR-325

teapots/choreographer-30fps/src/main/cpp/ChoreographerNativeActivity.cpp, teapots/classic-teapot/src/main/cpp/TeapotNativeActivity.cpp, teapots/common/ndk_helper/GLContext.cpp, teapots/common/ndk_helper/GLContext.h, teapots/more-teapots/src/main/cpp/MoreTeapotsNativeActivity.cpp
This fixes https://github.com/googlesamples/android-ndk/issues/439
Tested: Samsung Galaxy S6 Edge / Android 7.0
=> Teapot samples: bugfix for 439

camera/basic/src/main/java/com/sample/camera/basic/CameraActivity.java
A Pull Request can fix #464 memory leak bug, please test and merge it.
=> Fix #464 Memory Bug

.travis.yml
This should fix https://github.com/googlesamples/android-ndk/issues/469.  @DanAlbert  please take a look, thanks!
=> update travis.ci's NDK to r16b

endless-tunnel/app/src/main/cpp/data/our_shader.inl, endless-tunnel/app/src/main/cpp/shader.cpp
@jomof please take a look too, thanks!
=> Fix 73597988

display-p3/image-view/src/main/java/com/example/widecolor/WideColorActivity.java
so we have single layer at compositor, ending result is: only native image content is in play, UI TextViews are adding noisy to compositing anymore.
@bbilodeau @courtney-g PTAL, thanks!
=> Add popup window display duration ( 1 sec )

.ci_tools/build_samples.sh, .ci_tools/misc_ci.sh, .ci_tools/run_samples.sh, .ci_tools/setup_env.sh, .travis.yml, display-p3/README.md, hello-cdep/app/build.gradle, other-builds/experimental/hello-jni/app/build.gradle, other-builds/experimental/hello-jniCallback/app/build.gradle, other-builds/experimental/native-activity/app/build.gradle
=> Merge CI-Enabling code

camera/basic/build.gradle, camera/basic/src/main/cpp/CMakeLists.txt, camera/basic/src/main/cpp/camera_listeners.cpp, camera/basic/src/main/cpp/camera_manager.cpp, camera/basic/src/main/cpp/camera_manager.h, camera/basic/src/main/cpp/camera_ui.cpp, camera/basic/src/main/java/com/sample/camera/basic/CameraActivity.java, camera/texture-view/src/main/cpp/camera_manager.cpp, camera/texture-view/src/main/cpp/camera_manager.h, camera/texture-view/src/main/java/com/sample/textureview/ViewActivity.java
This should fix symptoms on emulator
=> Camera Sample: Adding checks for individual camera feature request

camera/basic/src/main/java/com/sample/camera/basic/CameraActivity.java
fix https://github.com/googlesamples/android-ndk/issues/543: avoiding crashing the app ( it is pure UI thing )
=> Camera Sample: catch & ignore exception from UI to avoid app crash

hello-neon/app/src/main/cpp/helloneon.c
=> Update the comment in helloneon.c

native-audio/app/src/main/cpp/native-audio-jni.c
=> Decorate return type with JNIEXPORT 

hello-gl2/app/build.gradle
this is for:
https://github.com/googlesamples/android-ndk/issues/594
=> hello-gl2: fix a typo

native-midi/README.md
mini change, will add formal doc to DAC and then delete all "how to use studio" things then
=> added more instruction to build native-midi with studio

.gitignore, display-p3/README.md, display-p3/image-view/src/main/cpp/AssetTexture.cpp, display-p3/image-view/src/main/cpp/ImageViewEngine.h, display-p3/image-view/src/main/cpp/WideColorCtx.cpp, display-p3/image-view/src/main/cpp/common.h
with EGL_EXT_gl_colorspace_display_p3_passthrough
Test: Pixel 3 XL Android 10
=> Update display-p3 sample

nn_sample/README.md
Updated the links filing an issue and forking the project.
=> Update the links in nn_sample/README.md

.ci_tools/build_samples.sh, hello-jni/app/build.gradle, hello-jni/app/src/main/cpp/hello-jni.c, hello-jni/app/src/main/java/com/example/hellojni/HelloJni.java, hello-jni/app/src/main/res/layout/activity_hello_jni.xml, hello-jni/build.gradle, hello-jni/gradle.properties, hello-jni/gradle/wrapper/gradle-wrapper.properties, other-builds/ndkbuild/hello-jni/app/build.gradle, other-builds/ndkbuild/hello-jni/build.gradle, other-builds/ndkbuild/hello-jni/gradle.properties, other-builds/ndkbuild/hello-jni/gradle/wrapper/gradle-wrapper.properties
this one patches up https://github.com/android/ndk-samples/pull/704 with:
- adding 32 bit into 64 bit productFlavor to comply with play store + 32 bit support
- update layout in resource to use androidx
- populate the change to ndk-build build directory
- update ci to reflect the changes above
=> Patch up PR 704 for a fix

nn-samples/README.md, nn-samples/basic/build.gradle, nn-samples/build.gradle, nn-samples/sequence/build.gradle, teapots/README.md, teapots/build.gradle, teapots/choreographer-30fps/build.gradle, teapots/classic-teapot/build.gradle, teapots/image-decoder/build.gradle, teapots/more-teapots/build.gradle, teapots/textured-teapot/build.gradle
=> Update R feature samples(nn-sample, image-decoder)

hello-oboe/README.md, hello-oboe/app/build.gradle, hello-oboe/app/src/main/cpp/CMakeLists.txt, hello-oboe/build.gradle, hello-oboe/gradle.properties, hello-oboe/gradle/wrapper/gradle-wrapper.properties
Test: Studio 4.0 beta4 on Mac with emulator
=> Update hello-oboe with pre-built lib

hello-libs/README.md, hello-libs/app/build.gradle, hello-libs/app/src/main/cpp/CMakeLists.txt, hello-libs/build.gradle, hello-libs/gradle/wrapper/gradle-wrapper.properties
Prepare to merge. https://github.com/android/ndk-samples/pull/724, with addition:
- 4.4.0 formal AGP version
- leave comment "shared lib manual packing for older agp versions" in readme.md: 4.0.0 is still too new, not covering all AGP users yet
=> Port github PR# 724

nn-samples/basic/build.gradle, nn-samples/build.gradle, nn-samples/sequence/build.gradle, teapots/README.md, teapots/build.gradle, teapots/image-decoder/build.gradle
just update to formal Studio 4.0.0 release
=> Update build script to AGP 4.0.0

hello-oboe/README.md, hello-oboe/app/build.gradle, hello-oboe/app/src/main/java/com/google/example/hellooboe/MainActivity.kt
- Small fixes.
Fixed a warning in the sample app:
This PR builds upon #730 . It should be reviewed/merged after #730 is merged.
=> Updated hello oboe sample

hello-libs/README.md
This is to fix https://github.com/android/ndk-samples/issues/744
=> Update README.md for hello-libs to fix issue 744

prefab/curl-ssl/app/src/main/cpp/http.cpp, teapots/image-decoder/src/main/cpp/Texture.cpp
=> adding assert.h/cassert into samples to be compliant to NDK-r23

nn-samples/basic/src/main/cpp/nn_sample.cpp, nn-samples/basic/src/main/cpp/simple_model.cpp, nn-samples/basic/src/main/cpp/simple_model.h
=> Workaround permission issue when loading NNAPI model from asset file.

hello-jni/app/build.gradle, hello-jni/app/src/main/AndroidManifest.xml, other-builds/ndkbuild/hello-jni/app/build.gradle
=> Fix lint errors for hello-jni.

hello-jniCallback/app/build.gradle, hello-jniCallback/app/src/main/AndroidManifest.xml
./gradlew lint reports no issues.
=> Fix lint errors for hello-jniCallback

hello-libs/app/build.gradle, hello-libs/app/src/main/AndroidManifest.xml, hello-libs/app/src/main/java/com/example/hellolibs/MainActivity.java, hello-libs/gradle.properties, other-builds/ndkbuild/hello-libs/app/build.gradle, other-builds/ndkbuild/hello-libs/gradle.properties
=> Fix lint errors for hello-libs

display-p3/image-view/build.gradle, display-p3/image-view/src/main/AndroidManifest.xml
=> Fix lint errors for display-p3

hello-gl2/app/build.gradle, hello-gl2/app/src/main/AndroidManifest.xml, other-builds/ndkbuild/hello-gl2/app/build.gradle
=> Fix lint errors for hello-gl2

hello-oboe/app/build.gradle, hello-oboe/app/src/main/AndroidManifest.xml
=> Fix lint errors for hello-oboe.

native-codec/app/build.gradle, native-codec/app/src/main/AndroidManifest.xml, other-builds/ndkbuild/native-codec/app/build.gradle
=> Fix lint errors with native-codec.

native-plasma/app/build.gradle, native-plasma/app/src/main/AndroidManifest.xml, other-builds/ndkbuild/native-plasma/app/build.gradle
=> Fix lint errors for native-plasma.

nn-samples/basic/build.gradle, nn-samples/basic/src/main/AndroidManifest.xml, nn-samples/sequence/build.gradle, nn-samples/sequence/src/main/AndroidManifest.xml, other-builds/ndkbuild/nn-samples/basic/build.gradle
=> Fix lint errors for nn-samples.

audio-echo/app/build.gradle, audio-echo/app/src/main/AndroidManifest.xml, audio-echo/app/src/main/res/menu/menu_main.xml
=> Fix lint errors for audio-echo.

native-activity/app/build.gradle, native-activity/app/src/main/AndroidManifest.xml, other-builds/ndkbuild/native-activity/app/build.gradle, other-builds/ndkbuild/native-activity/gradle.properties
=> Fix lint errors for native-activity.

sensor-graph/accelerometer/build.gradle, sensor-graph/accelerometer/src/main/AndroidManifest.xml
=> Fix lint errors for sensor-graph.

other-builds/ndkbuild/teapots/classic-teapot/build.gradle, other-builds/ndkbuild/teapots/more-teapots/build.gradle, teapots/choreographer-30fps/build.gradle, teapots/choreographer-30fps/src/main/AndroidManifest.xml, teapots/classic-teapot/build.gradle, teapots/classic-teapot/src/main/AndroidManifest.xml, teapots/image-decoder/build.gradle, teapots/image-decoder/src/main/AndroidManifest.xml, teapots/more-teapots/build.gradle, teapots/more-teapots/src/main/AndroidManifest.xml, teapots/textured-teapot/build.gradle, teapots/textured-teapot/src/main/AndroidManifest.xml
=> Fix lint errors for teapots.

.ci_tools/build_samples.sh, hello-neon/app/build.gradle, hello-neon/app/src/main/AndroidManifest.xml, other-builds/ndkbuild/hello-neon/app/build.gradle
=> Fix lint errors for hello-neon

bitmap-plasma/app/build.gradle, bitmap-plasma/app/src/main/AndroidManifest.xml, other-builds/ndkbuild/bitmap-plasma/app/build.gradle
=> Fix lint errors for bitmap-plasma.

prefab/prefab-dependency/app/build.gradle, prefab/prefab-dependency/app/src/main/AndroidManifest.xml
=> Fix lint errors for prefab-dependency.

webp/view/build.gradle, webp/view/src/main/AndroidManifest.xml, webp/view/src/main/cpp/CMakeLists.txt
=> Fix lint errors for webp.

audio-echo/app/build.gradle, camera/basic/build.gradle, camera/texture-view/build.gradle, display-p3/image-view/build.gradle, hello-jni/app/build.gradle, hello-jniCallback/app/build.gradle, hello-libs/app/build.gradle, hello-neon/app/build.gradle, hello-oboe/app/build.gradle, native-activity/app/build.gradle, native-audio/app/build.gradle, native-midi/app/build.gradle, nn-samples/basic/build.gradle, nn-samples/sequence/build.gradle, other-builds/ndkbuild/hello-jni/app/build.gradle, other-builds/ndkbuild/hello-libs/app/build.gradle, other-builds/ndkbuild/hello-neon/app/build.gradle, other-builds/ndkbuild/native-activity/app/build.gradle, other-builds/ndkbuild/native-audio/app/build.gradle, other-builds/ndkbuild/nn-samples/basic/build.gradle, prefab/curl-ssl/app/build.gradle, prefab/prefab-dependency/app/build.gradle, teapots/choreographer-30fps/build.gradle, teapots/classic-teapot/build.gradle, teapots/image-decoder/build.gradle, teapots/more-teapots/build.gradle, teapots/textured-teapot/build.gradle
androidx.appcompat:appcompat:1.5.1
androidx.constraintlayout:constraintlayout:2.1.4
androidx.core:core:1.9.0
com.android.support.constraint:constraint-layout:2.0.4 com.google.oboe:oboe:1.6.1
org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.21
org.jetbrains.kotlin:kotlin-stdlib:1.7.21
org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.1 org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1
=> Upgrade all obsolete dependencies.

.ci_tools/build_samples.sh, endless-tunnel/app/build.gradle, endless-tunnel/app/src/main/AndroidManifest.xml, hello-libs/gen-libs/build.gradle, other-builds/ndkbuild/san-angeles/app/build.gradle, other-builds/ndkbuild/two-libs/app/build.gradle, other-builds/ndkbuild/two-libs/app/src/main/AndroidManifest.xml, san-angeles/app/build.gradle, san-angeles/app/src/main/AndroidManifest.xml
endless-tunnel
hello-libs
two-libs
san-angeles
=> Update sdkVersion and fix lint errors I missed on the first pass.

bitmap-plasma/app/src/main/java/com/example/plasma/Plasma.java
App now resizes its bitmap during resize by implementing onSizeChanged in PlasmaView
=> Updating bitmap-plasma to better support large screen devices

sanitizers/app/build.gradle
Without this `./gradlew build` fails.
=> Only build HWASan buildType on arm64

hello-jni/README.md
Fixes https://github.com/android/ndk-samples/issues/845.
=> Remove obsolete instructions.

bitmap-plasma/.google/packaging.yaml, camera/.google/packaging.yaml, display-p3/.google/packaging.yaml, endless-tunnel/.google/packaging.yaml, exceptions/.google/packaging.yaml, gles3jni/.google/packaging.yaml, hello-gl2/.google/packaging.yaml, hello-jni/.google/packaging.yaml, hello-jniCallback/.google/packaging.yaml, hello-libs/.google/packaging.yaml, hello-oboe/.google/packaging.yaml, hello-vulkan/.google/packaging.yaml, native-activity/.google/packaging.yaml, native-codec/.google/packaging.yaml, native-media/.google/packaging.yaml, native-plasma/.google/packaging.yaml, san-angeles/.google/packaging.yaml, sanitizers/.google/packaging.yaml, sensor-graph/.google/packaging.yaml, teapots/.google/packaging.yaml, unit-test/.google/packaging.yaml, webp/.google/packaging.yaml
The service that reads these now only reads the top level one.
=> Remove unindexed packaging.yaml files.

README.md
It was wrong twice before (path and workflow name). I only fixed the workflow name last time. Also add the missing "actions" path component.
=> Really fix the status badge.

camera/basic/src/main/cpp/CMakeLists.txt, camera/texture-view/src/main/cpp/CMakeLists.txt, endless-tunnel/app/src/main/cpp/CMakeLists.txt, gles3jni/app/src/main/cpp/CMakeLists.txt, hello-gl2/app/src/main/cpp/CMakeLists.txt, hello-libs/app/src/main/cpp/CMakeLists.txt, hello-vulkan/app/src/main/cpp/CMakeLists.txt, native-activity/app/src/main/cpp/CMakeLists.txt, native-audio/app/src/main/cpp/CMakeLists.txt, native-codec/app/src/main/cpp/CMakeLists.txt, native-midi/app/src/main/cpp/CMakeLists.txt, prefab/curl-ssl/app/src/main/cpp/Application.mk, prefab/prefab-dependency/app/src/main/cpp/Application.mk, sensor-graph/accelerometer/src/main/cpp/CMakeLists.txt
C17 and C++17 are clang's default.
=> Stop downgrading C++ std.

gradle/libs.versions.toml, prefab/prefab-publishing/mylibrary/build.gradle, unit-test/app/build.gradle
Studio keeps bothering me to update AGP. This is that (and the other migrations).
=> Run upgrade assistant.

build-logic/src/main/java/com/android/ndk/samples/buildlogic/AndroidApplicationConventionPlugin.kt, build-logic/src/main/java/com/android/ndk/samples/buildlogic/AndroidLibraryConventionPlugin.kt
=> Enable 16k compat for all samples.

build-logic/src/main/java/com/android/ndk/samples/buildlogic/AndroidApplicationConventionPlugin.kt, build-logic/src/main/java/com/android/ndk/samples/buildlogic/AndroidLibraryConventionPlugin.kt, build-logic/src/main/java/com/android/ndk/samples/buildlogic/Versions.kt
The value I've set here is no different from the default, but soon it will be (hopefully), and this makes it easier to test a newer CMake.
=> Add plumbing for changing the CMake version.

hello-jniCallback/app/src/main/cpp/hello-jnicallback.c
This PR focuses on enhancing code readability and maintainability by introducing appropriate naming conventions for the JniHandler class and its associated usages in the sample app
=> Appropriate naming for JniHandler and associated usages

hello-jniCallback/app/src/main/cpp/CMakeLists.txt, hello-jniCallback/app/src/main/cpp/hello-jnicallback.cpp
Commits:
1. Convert to C++
2. Warning cleanup.
=> Cleanups in hello-jniCallback.

native-activity/README.md
I changed what this sample does but forgot to update the docs.
=> Update the native-activity README.

sanitizers/app/src/main/cpp/CMakeLists.txt, sanitizers/app/src/main/cpp/native-lib.cpp
It's a little bit strange to increase the warning level in a sample
that's intentionally doing bad things, but not *these* wrong things, so
it's still helpful to move the sample to `add_app_library` so we can
apply consistent behaviors throughout the repo.
=> Cleanup sanitizers sample.

README.md
We have the more refined version of this information on DAC now.
=> Point at DAC instead of duplicating docs.
